services:
  db:
    image: postgres:latest
    environment:
      - POSTGRESS_PASSWORD=${DB_PASSWORD}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: douglas@localhost.com
      PGADMIN_DEFAULT_PASSWORD: pgAdmin4CanDoIt